# Generated by Django 6.0.6 on 2026-06-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='notified_day_of',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='notified_one_hour_before',
            field=models.BooleanField(default=False),
        ),
    ]
