# Generated by Django 5.2 on 2026-06-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia', '0003_barbershop_profile_must_change_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='break_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Fim da Pausa'),
        ),
        migrations.AddField(
            model_name='profile',
            name='break_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Início da Pausa'),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_end',
            field=models.TimeField(default='20:00', verbose_name='Fim do Expediente'),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_start',
            field=models.TimeField(default='08:00', verbose_name='Início do Expediente'),
        ),
    ]
