# Generated by Django 5.2 on 2026-06-21 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia', '0004_profile_break_end_profile_break_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='work_end',
            field=models.TimeField(default=datetime.time(20, 0), verbose_name='Fim do Expediente'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_start',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Início do Expediente'),
        ),
    ]
